CollectionsManager.WEB/Models/Items/ItemToEditViewModel.cs
using System;
using System.Collections.Generic;
using CollectionManager.WEB.Models.Tags;
using CollectionsManager.BLL.DTO.CustomFields;
using CollectionsManager.BLL.DTO.Tags;

namespace CollectionManager.WEB.Models.Items
{
    public class ItemToEditViewModel
    {
        public Guid Id { get; set; }

        public Guid CollectionId { get; set; }

        public string CurrentUserId { get; set; }

        public string Name { get; set; }

        public IList<TagDto> Tags { get; set; }

        public IList<ExistedTagToEditViewModel> ExistedTags { get; set; }

        public IList<CustomFieldValueToManipulateDto> CustomFields { get; set; }
    }
}

CollectionsManager.WEB/Models/Items/SearchModel.cs
namespace CollectionManager.WEB.Models.Items
{
    public class SearchModel
    {
        public string SearchString { get; set; }
    }
}

CollectionsManager.WEB/Controllers/CommentsController.cs
using System;
using System.Threading.Tasks;
using CollectionManager.WEB.Extensions;
using CollectionsManager.BLL.DTO.Comments;
using CollectionsManager.BLL.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionManager.WEB.Controllers
{
    public class CommentsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CommentsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> PostComment(CommentToCreateDto comment)
        {
            comment.AuthorId = User.GetUserId();

            await _unitOfWork.Comments.CreateComment(comment);

            return RedirectToAction("Details", "Items", new { comment.ItemId });
        }

        [HttpGet]
        public async Task<IActionResult> GetCommentsForItem(Guid itemId)
            => Json(await _unitOfWork.Comments.GetCommentsByItemId(itemId));
    }
}

CollectionsManager.WEB/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CollectionManager.WEB.Extensions;
using CollectionManager.WEB.Models.Items;
using CollectionsManager.BLL.DTO.Items;
using CollectionsManager.BLL.DTO.Tags;
using CollectionsManager.BLL.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionManager.WEB.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ISearchService _searchService;

        public ItemsController(IUnitOfWork unitOfWork, IMapper mapper, ISearchService searchService)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _searchService = searchService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid itemId)
            => View(await _unitOfWork.Items.GetItemDetailsAsync(itemId));

        [HttpGet]
        public async Task<IActionResult> AddItemToCollection(Guid collectionId)
            => View(await _unitOfWork.Items.GetItemToAddAsync(collectionId));

        [HttpPost]
        public async Task<IActionResult> AddItemToCollection(ItemToCreate item)
        {
            if (!ModelState.IsValid)
                return View(item);

            await _unitOfWork.Items.CreateItemAsync(item);

            return RedirectToCollectionDetails(item.CollectionId);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid itemId)
        {
            var item = await _unitOfWork.Items.GetItemToEditAsync(itemId);

            return View(_mapper.Map<ItemToEditViewModel>(item));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ItemToEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var dto = _mapper.Map<ItemToEditDto>(model);
            dto.CurrentUserId = User.GetUserId();
            var tags = new List<string>();

            if (model.ExistedTags is not null)
            {
                tags = model.ExistedTags
                    .Where(x => x.ToRemove == false)
                    .Select(x => x.Name)
                    .ToList();
            }

            if (model.Tags is not null)
            {
                tags = tags.Union(model.Tags.Select(x => x.Name)).ToList();
            }
               
            dto.Tags = tags.Select(tagName => new TagDto { Name = tagName });

            await _unitOfWork.Items.UpdateItemAsync(dto);

            return RedirectToAction("Details", new { itemId = model.Id });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string substring)
        {
            var items = await _searchService.SearchBySubstringAsync(substring);

            return View("SearchResult", _mapper.Map<IEnumerable<FoundItemToReturnDto>>(items));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> SearchByTag(string tag)
            => View("SearchResult", await _unitOfWork.Items.GetByTagAsync(tag));

        public async Task<IActionResult> Delete(Guid itemId, Guid collectionId)
        {
            await _unitOfWork.Items.DeleteItemAsync(itemId, User.GetUserId());

            return RedirectToCollectionDetails(collectionId);
        }

        private RedirectToActionResult RedirectToCollectionDetails(Guid collectionId)
            => RedirectToAction("CollectionDetails", "Collections", new { collectionId });
    }
}

CollectionsManager.WEB/Controllers/LikesController.cs
using System;
using System.Threading.Tasks;
using CollectionManager.WEB.Extensions;
using CollectionsManager.BLL.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionManager.WEB.Controllers
{
    public class LikesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public LikesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> PutLike(Guid itemId)
        {
            if (User.Identity is { IsAuthenticated: false })
            {
                return RedirectToAction("SignIn", "Account");
            }

            await _unitOfWork.Likes.PutLikeAsync(itemId, User.GetUserId());

            return RedirectToItemDetails(itemId);
        }

        [Authorize]
        public async Task<IActionResult> RemoveLike(Guid itemId)
        {
            await _unitOfWork.Likes.RemoveLikeAsync(itemId, User.GetUserId());

            return RedirectToItemDetails(itemId);
        }

        private RedirectToActionResult RedirectToItemDetails(Guid itemId)
            => RedirectToAction("Details", "Items", new { itemId });
    }
}

CollectionsManager.WEB/Views/Items/AddItemToCollection.cshtml
@using CollectionsManager.DAL.Constants
@model CollectionsManager.BLL.DTO.Items.ItemToCreate

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add Item To Collection</title>
</head>
<body>

<div class="text-center" style="margin-top: 10px;"><h4>Create Item</h4></div>

    <div class="row justify-content-center">
        <div class="col-md-6">

            <form asp-action="AddItemToCollection" id="addItemForm">
                @Html.HiddenFor(x => x.CollectionId)

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" autocomplete="off" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                @{
                    for (int i = 0; i < Model.CustomFieldValuesToCreate.Count; i++)
                    {
                        @Html.HiddenFor(x => x.CustomFieldValuesToCreate[i].CustomFieldId)
                        @Html.HiddenFor(x => x.CustomFieldValuesToCreate[i].Type)

                        <div class="form-group">
                            @Html.DisplayFor(x => x.CustomFieldValuesToCreate[i].Name)

                            @switch (Model.CustomFieldValuesToCreate[i].Type)
                            {
                                case CustomPropertyType.DateTime:
                                    <input asp-for="@Model.CustomFieldValuesToCreate[i].Value" type="datetime-local" class="form-control" />break;

                                case CustomPropertyType.Bool:
                                    <br/><input asp-for="@Model.CustomFieldValuesToCreate[i].Value" type="checkbox" class="form-check-input" />break;

                                default:
                                    <input asp-for="@Model.CustomFieldValuesToCreate[i].Value" autocomplete="off" class="form-control" />break;
                            }
                            @Html.ValidationMessageFor(x => x.CustomFieldValuesToCreate[i].Value)
                        </div>
                    }
                }

                <div class="form-group">
                    <dl class="row">
                        <dt class="col-sm-2">
                            Tags:
                        </dt>
                        <dd class="col-sm-10">
                            <span id="tagsRow"></span>
                        </dd>
                    </dl>
                </div>

                <div class="form-group" id="tagInputBlock">
                    <input type="text" id="tagInput" class="form-control" autocomplete="off" placeholder="Type a tag..." />

                    <button type="button" id="addTagButton" class="btn btn-secondary" style="margin-top: 10px;">Add tag</button>

                    <div class="tags-list-block">
                        <ul class="tags-ul" id="tagsList">
                        </ul>
                    </div>
                </div>

                <div class="form-group text-center">
                    <input type="submit" value="Create" class="btn btn-primary" style="padding-left: 30px; padding-right: 30px" />
                </div>
            </form>
        </div>
    </div>
    <script src="~/js/TagsScript.js" asp-append-version="true"></script>
</body>
</html>

CollectionsManager.WEB/Views/Items/Details.cshtml
@using CollectionManager.WEB.Extensions
@model CollectionsManager.BLL.DTO.Items.ItemDetailsToReturnDto

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Item Details</title>
    <link rel="stylesheet" href="~/css/ItemDetails.css" />
</head>
<body>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="text-center" style="margin-top: 10px"><h4>Item Details</h4></div>
        <hr/>
        <div class="col-md-6">
            <dl class="row">
                @Html.HiddenFor(model => model.Id, new {id ="itemId"})

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Id)
                </dt>
                <dd class="col-sm-10 item-details-dd">
                    @Html.DisplayFor(model => model.Id)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10 item-details-dd">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CollectionName)
                </dt>
                <dd class="col-sm-10 item-details-dd">
                    @Html.DisplayFor(model => model.CollectionName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.OwnerName)
                </dt>
                <dd class="col-sm-10 item-details-dd">
                    @Html.DisplayFor(model => model.OwnerName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CollectionId)
                </dt>
                <dd class="col-sm-10 item-details-dd">
                    @Html.DisplayFor(model => model.CollectionId)
                </dd>

                @foreach (var field in Model.CustomFieldValues)
                {
                    <dt class="col-sm-2">
                        @Html.DisplayFor(x => field.Name)
                    </dt>
                    <dd class="col-sm-10 item-details-dd">
                        @Html.DisplayFor(x => field.Value)
                    </dd>
                }

                <dt class="col-sm-2">
                    Tags
                </dt>
                <dd class="col-sm-10 item-details-dd">
                    @string.Join(", ", Model.Tags.Select(x => x.Name))
                </dd>
            </dl>
            
            <div class="text-end">
                @if (Model.Likes.Any(x => x.AuthorId == User.GetUserId()))
                {
                    <button class="btn btn-outline-danger like-button" onclick="location.href = '@Url.Action("RemoveLike", "Likes", new { itemId = Model.Id })'"><i class="bi bi-heart"></i> @Model.Likes.Count()</button>
                }
                else
                {
                    <button class="btn btn-outline-secondary like-button" onclick="location.href = '@Url.Action("PutLike", "Likes", new { itemId = Model.Id })'"><i class="bi bi-heart"></i> @Model.Likes.Count()</button>
                }
            </div>

            @if (User.Identity is { IsAuthenticated: true })
            {
                <div style="margin-top: 10px;">
                    <form asp-action="PostComment" asp-controller="Comments">

                        <input type="hidden" name="itemId" value="@Model.Id"/>
                        @Html.TextArea("CommentText", null, new { data_val = "true", data_val_required = "Text is required", @class = "form-control", rows="2", autocomplete="off", placeholder = "Type comment..." })
                        <span class="text-danger" data-valmsg-for="CommentText" data-valmsg-replace="true"></span><br/>
                        
                        <div class="text-center">
                            <input style="padding-right: 30px; padding-left: 30px" type="submit" value="Post" class="btn btn-primary"/>
                        </div>
                    </form>
                </div>
            }
            
            <div class="container my-5 py-5" id="commentsContainer" style="display: none">
                <div class="text-center"><h5>Comments</h5></div>
                <div class="row d-flex justify-content-center">
                    <div class="col-md-10">
                        <div class="card text-dark" id="commentsBlock" style="margin: auto;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/UpdatingCommentsScript.js" asp-append-version="true"></script>
</body>
</html>

CollectionsManager.WEB/Views/Items/Edit.cshtml
@using CollectionsManager.DAL.Constants
@model CollectionManager.WEB.Models.Items.ItemToEditViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <div class="text-center" style="margin-top: 10px;"><h4>Edit Item</h4></div>

<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Edit" id="addItemForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CollectionId)

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            @for (int i = 0; i < Model.CustomFields.Count; i++)
            {
                @Html.HiddenFor(x => x.CustomFields[i].CustomFieldId)
                @Html.HiddenFor(x => x.CustomFields[i].Name)
                @Html.HiddenFor(x => x.CustomFields[i].Type)
                @Html.HiddenFor(x => x.CustomFields[i].Id)
                @Html.HiddenFor(x => x.CustomFields[i].ItemId)

                <div class="form-group">
                    <label asp-for="@Model.CustomFields[i]" class="control-label">@Model.CustomFields[i].Name</label>

                    @switch (Model.CustomFields[i].Type)
                    {
                        case CustomPropertyType.DateTime:
                            <input asp-for="@Model.CustomFields[i].Value" type="datetime-local" class="form-control" />
                            break;

                        case CustomPropertyType.Bool:
                            <input asp-for="@Model.CustomFields[i].Value" type="checkbox" class="form-control" />
                            break;

                        default:
                            <input asp-for="@Model.CustomFields[i].Value" class="form-control" />
                            break;
                    }

                    <span asp-validation-for="@Model.CustomFields[i].Value" class="text-danger"></span>
                </div>
            }

            <dl class="row">
                <dt class="col-sm-2">
                    Tags:
                </dt>
                <dd class="col-sm-10">
                    <span id="tagsRow"></span>
                </dd>
            </dl>

            <div class="form-group" id="tagInputBlock">
                <input type="text" id="tagInput" class="form-control" autocomplete="off" placeholder="Type a tag..." />

                <button type="button" id="addTagButton" class="btn btn-secondary" style="margin-top: 10px;">Add tag</button>

                <div class="tags-list-block">
                    <ul class="tags-ul" id="tagsList">
                    </ul>
                </div>
            </div>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Remove
                    </th>
                </tr>
                </thead>
                <tbody>
                @for (int i = 0; i < Model.ExistedTags.Count; i++)
                {
                    @Html.HiddenFor(x => Model.ExistedTags[i].Name)
                    <tr>
                        <td>
                            @Html.DisplayFor(x => Model.ExistedTags[i].Name)
                        </td>
                        <td>
                            @Html.CheckBoxFor(x => Model.ExistedTags[i].ToRemove)
                        </td>
                    </tr>
                }
                </tbody>
            </table>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<script src="~/js/TagsScript.js" asp-append-version="true"></script>
</body>
</html>

CollectionsManager.WEB/Views/Items/SearchResult.cshtml
@model IEnumerable<CollectionsManager.BLL.DTO.Items.FoundItemToReturnDto>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
</head>
<body>

    @if (Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CollectionName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.OwnerName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tags)
                    </th>
                    <th class="text-center">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CollectionName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OwnerName)
                        </td>
                        <td>
                            @foreach (var tag in item.Tags)
                            {
                                @Html.ActionLink(tag, "SearchByTag", "Items", new { tag }, new {@class = "tag-link"})
                            }
                        </td>
                        <td class="text-center">
                            @Html.ActionLink("To Collection", "CollectionDetails", "Collections", new { collectionId = item.CollectionId }, new { @class = "table-link" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p style="margin-left: 20px; margin-top: 20px; font-style: italic;">Nothing found</p>
    }
</body>
</html>