CollectionsManager.WEB/Controllers/CollectionsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CollectionManager.WEB.Extensions;
using CollectionManager.WEB.Models;
using CollectionsManager.BLL.DTO.Collections;
using CollectionsManager.BLL.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionManager.WEB.Controllers
{
    [Authorize]
    public class CollectionsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CollectionsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> UsersCollections(Guid userId)
            => View(await _unitOfWork.Collections.GetCollectionsByUserAsync(userId));

        [HttpPost]
        public IActionResult GetMarkDownPreview([FromBody] MarkDownViewModel model)
            => PartialView(model);

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> CollectionDetails(Guid collectionId)
            => View(await _unitOfWork.Collections.GetCollectionDetailsAsync(collectionId));

        [HttpGet]
        public IActionResult CreateCollection()
            => View();

        [HttpPost]
        public async Task<IActionResult> CreateCollection(CollectionToManipulateDto model)
        {
            if (!ModelState.IsValid)
                return View();

            model.OwnerId = User.GetUserId();
            await _unitOfWork.Collections.CreateCollectionAsync(model);

            return RedirectToIndex();
        }

        [HttpGet]
        public async Task<IActionResult> EditCollection(Guid collectionId)
            => View(await _unitOfWork.Collections.GetCollectionToEditAsync(collectionId));

        [HttpPost]
        public async Task<IActionResult> EditCollection(CollectionToManipulateDto model)
        {
            if (!ModelState.IsValid)
                return View(await _unitOfWork.Collections.GetCollectionToEditAsync(model.Id));

            model.CustomFields = model.CustomFields?.Where(x => x.ToRemove == false).ToList();
            model.OwnerId = User.GetUserId();

            await _unitOfWork.Collections.UpdateCollectionAsync(model);

            return RedirectToIndex();
        }

        public async Task<IActionResult> DeleteCollection(Guid collectionId)
        {
            await _unitOfWork.Collections.DeleteCollectionAsync(collectionId, User.GetUserId());

            return RedirectToIndex();
        }

        private RedirectToActionResult RedirectToIndex()
            => RedirectToAction("UsersCollections", new { userId = User.GetUserId() });
    }
}

CollectionsManager.WEB/Views/Shared/Components/LargestCollections/LargestCollectionsView.cshtml
@using CollectionManager.WEB.Extensions
@model IEnumerable<CollectionsManager.BLL.DTO.Collections.LargestCollectionToReturnDto>

<div class="container-fluid">
    <div class="row justify-content-around">
        <div class="text-center">
            <h4>Largest collections</h4>
        </div>

        @foreach (var collection in Model)
        {
            <div class="col-md-auto">
                <div class="card">
                    <img src="@collection.ImageSource" class="card-img-top custom-card-img" alt=":(">
                    <div class="card-body custom-card-body">
                        <h5 class="card-title custom-card-title">@collection.Name</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Items count: @collection.ItemsCount</h6>
                        <h6 class="card-subtitle mb-2 text-muted">Owner: @collection.OwnerName</h6>
                    </div>
                    <div class="bottom-card-block text-center">
                        @Html.ActionLink("Details", "CollectionDetails", "Collections", new { collectionId = collection.Id }, new { @class = "btn btn-primary btn-sm" })

                        @if (User.IsUserHasAccess(collection.OwnerId))
                        {
                            @Html.ActionLink("Edit", "EditCollection", "Collections", new { collectionId = collection.Id }, new { @class = "btn btn-warning btn-sm", style = "margin-right: 5px;" })
                            @Html.ActionLink("Delete", "DeleteCollection", "Collections", new { collectionId = collection.Id }, new { @class = "btn btn-danger btn-sm" })
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>