CollectionsManager.WEB/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CollectionManager.WEB.Extensions;
using CollectionManager.WEB.Models.Items;
using CollectionsManager.BLL.DTO.Items;
using CollectionsManager.BLL.DTO.Tags;
using CollectionsManager.BLL.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionManager.WEB.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ISearchService _searchService;

        public ItemsController(IUnitOfWork unitOfWork, IMapper mapper, ISearchService searchService)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _searchService = searchService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid itemId)
            => View(await _unitOfWork.Items.GetItemDetailsAsync(itemId));

        [HttpGet]
        public async Task<IActionResult> AddItemToCollection(Guid collectionId)
            => View(await _unitOfWork.Items.GetItemToAddAsync(collectionId));

        [HttpPost]
        public async Task<IActionResult> AddItemToCollection(ItemToCreate item)
        {
            if (!ModelState.IsValid)
                return View(item);

            await _unitOfWork.Items.CreateItemAsync(item);

            return RedirectToCollectionDetails(item.CollectionId);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid itemId)
        {
            var item = await _unitOfWork.Items.GetItemToEditAsync(itemId);

            return View(_mapper.Map<ItemToEditViewModel>(item));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ItemToEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var dto = _mapper.Map<ItemToEditDto>(model);
            dto.CurrentUserId = User.GetUserId();
            var tags = new List<string>();

            if (model.ExistedTags is not null)
            {
                tags = model.ExistedTags
                    .Where(x => x.ToRemove == false)
                    .Select(x => x.Name)
                    .ToList();
            }

            if (model.Tags is not null)
            {
                tags = tags.Union(model.Tags.Select(x => x.Name)).ToList();
            }
               
            dto.Tags = tags.Select(tagName => new TagDto { Name = tagName });

            await _unitOfWork.Items.UpdateItemAsync(dto);

            return RedirectToAction("Details", new { itemId = model.Id });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string substring)
        {
            var items = await _searchService.SearchBySubstringAsync(substring);

            return View("SearchResult", _mapper.Map<IEnumerable<FoundItemToReturnDto>>(items));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> SearchByTag(string tag)
            => View("SearchResult", await _unitOfWork.Items.GetByTagAsync(tag));

        public async Task<IActionResult> Delete(Guid itemId, Guid collectionId)
        {
            await _unitOfWork.Items.DeleteItemAsync(itemId, User.GetUserId());

            return RedirectToCollectionDetails(collectionId);
        }

        private RedirectToActionResult RedirectToCollectionDetails(Guid collectionId)
            => RedirectToAction("CollectionDetails", "Collections", new { collectionId });
    }
}

CollectionsManager.WEB/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CollectionManager.WEB.Extensions;
using CollectionManager.WEB.Models.Users;
using CollectionsManager.BLL.Services.Interfaces;
using CollectionsManager.DAL.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionManager.WEB.Controllers
{
    [Authorize(Roles = nameof(RoleNames.Admin))]
    public class UsersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public UsersController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _unitOfWork.Users.GetAllAsync();

            return View(_mapper.Map<IList<UserViewModel>>(users));
        }

        [HttpPost]
        public async Task<IActionResult> HandleChangingRoles(IList<UserViewModel> users, string submit)
        {
            var selectedUserId = users
                .Where(x => x.IsSelected)
                .Select(x => x.Id)
                .FirstOrDefault();

            if (selectedUserId is not null)
            {
                switch (submit)
                {
                    case "AddAdminRole":
                        await _unitOfWork.Users.AddAdminRoleAsync(selectedUserId, User.GetUserId());
                        break;

                    case "RemoveAdminRole":
                        await _unitOfWork.Users.RemoveAdminRoleAsync(selectedUserId, User.GetUserId());
                        break;

                    case "Block":
                        await _unitOfWork.Users.BlockAsync(selectedUserId, User.GetUserId());
                        break;

                    case "Unblock":
                        await _unitOfWork.Users.UnblockAsync(selectedUserId, User.GetUserId());
                        break;
                }
            }

            return RedirectToAction("Index");
        }
    }
}

CollectionsManager.WEB/Views/Shared/_Layout.cshtml
@using CollectionManager.WEB.Extensions
@using CollectionsManager.DAL.Constants

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="container-fluid">
            @Html.ActionLink("Collections Manager", "Index", "Home", null, new { @class = "btn btn-outline-primary main-page-link" })

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item" style="visibility: hidden;">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <form asp-controller="Items" asp-action="Search" method="get" class="d-flex" >
                            <input class="form-control me-2" name="substring" type="search" data-val="true" data-val-required="" placeholder="Search" aria-label="Search" autocomplete="off">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </li>
                </ul>
                <div class="d-flex">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <div class="hello-block"><span style="color: seagreen">Hello, @User.GetUserName()</span></div>
                                </li>

                                @if (User.IsInRole(RoleNames.Admin.ToString()))
                                {
                                    <li class="nav-item">
                                        @Html.ActionLink("Admin Panel", "Index", "Users", null, new { @class = "btn btn-outline-warning login-button" })
                                    </li>
                                }

                                <li class="nav-item">
                                    @Html.ActionLink("My Collections", "UsersCollections", "Collections", new { userId = User.GetUserId() }, new { @class = "btn btn-outline-success login-button" })
                                </li>

                                <li class="nav-item">
                                    @Html.ActionLink("Logout", "Logout", "Account", routeValues: null, new { @class = "btn btn-outline-primary login-button" })
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    @Html.ActionLink("Sign In", "SignIn", "Account", routeValues: null, new { @class = "btn btn-outline-primary login-button" })
                                </li>
                                <li class="nav-item">
                                    @Html.ActionLink("Sign Up", "SignUp", "Account", routeValues: null, new { @class = "btn btn-outline-primary login-button" })
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

    @RenderBody()

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>